#!/usr/bin/env python3
''' 
Description: Import async_generator from the prev task & define a 
             coroutine named async_comprehension with no ars. The 
             coroutine uses async comprehension to collect 10 random numbers 
             generated by async_generator & then returns the list of these 
             10 random numbers.
'''

from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    ''' 
    Return a list of vals yielded by async_generator using async 
    comprehension.
    '''
    return [value async for value in async_generator()]